[cse]
cseID = id-in
cseName = cse-in
cseType = IN

[server]
httpPort = 8080
enableRemoteCSE = True

[database]
# Path where ACME will store its persistent data (must match docker-compose volume)
path = /cse/data

[logging]
# Path where logs and other runtime files should be stored
logPath = /cse/data

[security]
# Enable HTTP Basic Authentication and point to the credentials file inside the mounted cse directory
enableHttpBasicAuth = True
httpBasicAuthFile = /cse/certs/http_basic_auth.txt
