[Interface]
Address = 10.100.0.1/24
ListenPort = 51820
PrivateKey = aObUwOO3ocYn3kN1XJWaVu5RpAZCJ2AG1Vo0NQX+xlQ=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -I INPUT -p tcp -s 10.100.0.2 --dport 8080 -j ACCEPT; iptables -I INPUT -p tcp -s 10.100.0.4 --dport 8080 -j ACCEPT; iptables -I INPUT -p tcp --dport 8080 -j DROP
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -D INPUT -p tcp -s 10.100.0.2 --dport 8080 -j ACCEPT || true; iptables -D INPUT -p tcp -s 10.100.0.4 --dport 8080 -j ACCEPT || true; iptables -D INPUT -p tcp --dport 8080 -j DROP || true

[Peer]
# Alper
PublicKey = VjtPF8pxIXJMUs//96E0Y7kv4K6rTjLyyjR9VnPfBHU=
AllowedIPs = 10.100.0.2/32, 192.168.123.0/24 # Alper LAN subnet

[Peer]
# Benjamin
PublicKey = ompdo0Gc+oenG2KH98asvMwEKDMruOs3bjd484SS4nk=
AllowedIPs = 10.100.0.3/32, 192.168.2.0/24 # Placeholder for Benjamin's LAN

[Peer]
# Tahir
PublicKey = lZgTAy9zmjWDE/Ji4f3u61178HMoH/9iYdwR+HqMxTA=
AllowedIPs = 10.100.0.4/32, 192.168.3.0/24 # Placeholder for Tahir's LAN
